### ISSUE TITLE
spinner can't be resize

### ISSUE THREAD

**Issue by vega3000** [YeongCheon/ngx-pull-to-refresh#18]
For my PWA, the spinner si very to big.
It's impossible to resize the spinner because CustomClass is bind to ngx-ptr-content-container, not on ngx-ptr-spinner.

My work around is using
```
:host ::ng-deep .ngx-ptr-spinner {
    width: 10% !important;
    margin-top: -135px !important;
}
```

Maybe it will be a good idea to add a specific Class for the spinner.

Best regards

**Comment by YeongCheon** [comment]
you can use `spinnerSize` attribute.

for example

```
<ngx-pull-to-refresh
	spinnerColor="#ff0000"
	distanceForRefresh="40"
	spinnerSize="100px" // use this
	[isEnable]="isEnable"
	[targetElement]="targetElement"
	(refresh)="myRefreshEvent($event, 'refresh')"
	(loadMore)="alert('loadmore')"
	style="display:block;height:100%;">
  <div style="height: 3000px">long content</div>
```

i forgot update README file. sorry.
i will update soon.
