### ISSUE TITLE
readme error

### ISSUE THREAD

**Issue by Program-arg** [YeongCheon/ngx-pull-to-refresh#24]
Readme:
**import { NgxPullToRefreshModule } from 'ngx-pull-to-refresh.module';**

Correct use:
**import { NgxPullToRefreshModule } from 'ngx-pull-to-refresh';**

**Comment by YeongCheon** [comment]
thanks. it updated the document.(commit: [6bffed2a4dfe4280e49700882d9b69b8deea548f](https://github.com/YeongCheon/ngx-pull-to-refresh/commit/6bffed2a4dfe4280e49700882d9b69b8deea548f))
