### ISSUE TITLE
Google Fonts are not GDPR conform

### ISSUE THREAD

**Issue by TommyBom** [YeongCheon/ngx-pull-to-refresh#46]
https://github.com/YeongCheon/ngx-pull-to-refresh/blob/f504396a3eaba32551fe7ffb0c3e712ebcce12ef/projects/ngx-pull-to-refresh/src/lib/ngx-pull-to-refresh.component.scss#L1

In this file, theres a static import of google fonts. 
Please remove this / repalce this with a static local variant.

**Comment by YeongCheon** [comment]
i merged [this](https://github.com/YeongCheon/ngx-pull-to-refresh/pull/47).


I will complete the npm deployment as soon as possible.

**Comment by YeongCheon** [comment]
npm package publish completed!

use `15.0.2` version

@BBosman help us. thank you!
