### ISSUE TITLE
The component's scroll event blocks the parent label's scroll event.

### ISSUE THREAD

**Issue by skyopens** [YeongCheon/ngx-pull-to-refresh#52]
Currently using version: 13.0.0.
The distance judgment of loadMore is too early. My project is required to perform the requested operation after scrolling to the bottom of the page:
HTML:
```
<div class="content_box" id="scroll_box">
        <ngx-pull-to-refresh [spinnerSize]="34">
                 // the list....
        </ngx-pull-to-refresh>
</div>
```
JS:
```
        const scrollBox = this.render2.selectRootElement('#scroll_box', true);
        fromEvent(scrollBox, 'scroll').pipe(debounceTime(400)).subscribe(() => {
                alert('It is scrolling');
                // do something
        });
```
Alert was not executed. I guessed that the ev.stopPropagation operation was performed internally.Although I can listen through the class name specified by customClass, this approach is not convenient in some cases.

It is hoped that the configuration item can be exposed to prevent bubbling events, or the distance judgment of loadMore can be changed to a configurable item.

Kind Regards.

**Comment by YeongCheon** [comment]
I'm using an older version of the library, so I don't remember exactly. If the scroll area is a `#scroll_box` rather than a window, try using the `[targetElement]` property to specify the scroll target.

``` html
<div class="content_box" id="scroll_box" #scrollBox>
        <ngx-pull-to-refresh [spinnerSize]="34" [targetElement]="scrollBox">
                 // the list....
        </ngx-pull-to-refresh>
</div>
```
