### ISSUE TITLE
How to use this with Angular app

### ISSUE THREAD

**Issue by Sampath-Lokuge** [YeongCheon/ngx-pull-to-refresh#6]
Hi,

Can you tell me simple steps to how to use this with the Angular 10 app? It seems so complicated to understand what you have mentioned. Is this do not have an Angular module to import and use that directly on the component?

Why do I need this? Can't I use this only? `npm i ngx-pull-to-refresh`

>Run ng generate component component-name --project ngx-pull-to-refresh to generate a new component. You can also use ng generate directive|pipe|service|class|guard|interface|enum|module --project ngx-pull-to-refresh.

**Comment by YeongCheon** [comment]
please see [example code](https://github.com/YeongCheon/ngx-pull-to-refresh/tree/master/projects/example)

**Comment by Sampath-Lokuge** [comment]
Yes, I saw that. But the problem is this line `import { NgxPullToRefreshModule } from 'projects/ngx-pull-to-refresh/src/lib/ngx-pull-to-refresh.module';` What is this? Can't I use this directly with npm?

**Comment by YeongCheon** [comment]
follow this step.


1. use `npm i ngx-pull-to-refresh` command.
2. import `NgxPullToRefreshModule` to your module.
``` typescript
import { NgxPullToRefreshModule } from 'ngx-pull-to-refresh';

@NgModule({
  imports: [
    NgxPullToRefreshModule,
  ]
})
export class YourModule { }


```
3. use `ngx-pull-to-refresh` tag in your html file.
``` html
<ngx-pull-to-refresh
  spinnerColor="#ff0000"
  spinnerSize="50px"
  (refresh)="myRefreshEvent($event, 'refresh')"
  (loadMore)="alert('loadmore')"
  style="display:block;height:100%;">
  <div style="height: 3000px">long content</div>
</ngx-pull-to-refresh>

```

**Comment by Sampath-Lokuge** [comment]
Please put this on the Readme file. It is so confusing right now. You have developed a great module. But super confusing readme file. I hope you'll put this content there. Thanks!
